name: OWASP ZAP DAST Scan

on:
  push:
  pull_request:

jobs:
  securityscanjob:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app Docker image
        run: docker build -t clickseguro-app .

      - name: Create Docker network
        run: docker network create zapnet

      - name: Run application container
        run: |
          docker run -d --name clickseguro-app --network zapnet clickseguro-app
          echo "Aguardando app subir..."
          for i in {1..30}; do
            if curl -sSf http://clickseguro-app:8080 >/dev/null; then
              echo "✅ App está acessível"
              break
            fi
            echo "⏳ Esperando app..."
            sleep 2
          done

      - name: Prepare writable folder for reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      - name: Run OWASP ZAP Full Scan and generate alert report
        run: |
          docker run --rm --network zapnet \
            -v ${{ github.workspace }}/zap_reports:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://clickseguro-app:8080 \
            -r scan-summary.html \
            -J report.json \
            -w report.md \
            -f html \
            -o /zap/wrk/alert-report.html \
            -I -d || true

      - name: List ZAP reports
        run: ls -lh zap_reports

      - name: Parse JSON and fail if HIGH or CRITICAL found
        run: |
          echo "🔍 Analisando relatório JSON..."
          if [ ! -f "zap_reports/report.json" ]; then
            echo "⚠️ Arquivo report.json não encontrado."
            exit 0
          fi

          HIGH_COUNT=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' zap_reports/report.json)
          CRITICAL_COUNT=$(jq '[.site[].alerts[] | select(.risk == "Critical")] | length' zap_reports/report.json)

          echo "⚠️ Vulnerabilidades High: $HIGH_COUNT"
          echo "🚨 Vulnerabilidades Critical: $CRITICAL_COUNT"

          if [ "$HIGH_COUNT" -gt 0 ] || [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Vulnerabilidades graves detectadas."
            exit 1
          fi

      - name: Upload ZAP reports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap_reports/

      - name: Cleanup
        if: always()
        run: |
          docker rm -f clickseguro-app || true
          docker network rm zapnet || true
