name: OWASP ZAP DAST Scan

on:
  push:
  pull_request:

jobs:
  securityscanjob:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Construir imagem da aplicação
      - name: Build app Docker image
        run: docker build -t clickseguro-app .

      # 4️⃣ Criar rede Docker customizada
      - name: Create Docker network
        run: docker network create zapnet

      # 5️⃣ Subir container da aplicação
      - name: Run application container
        run: |
          docker run -d --name clickseguro-app --network zapnet clickseguro-app
          echo "Aguardando app subir..."
          for i in {1..30}; do
            if curl -sSf http://clickseguro-app:8080 >/dev/null; then
              echo "✅ App está acessível"
              break
            fi
            echo "⏳ Esperando app..."
            sleep 2
          done

      # 6️⃣ Criar pasta com permissões para relatórios
      - name: Prepare writable folder for reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      # 7️⃣ Rodar o OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --name zap-scanner --network zapnet \
            -v ${{ github.workspace }}/zap_reports:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://clickseguro-app:8080 \
            -r scan-summary.html -J report.json -w report.md -I -d || true

      # 8️⃣ Gerar relatório HTML com alertas via API
      - name: Generate alert report using ZAP API
        run: |
          docker exec zap-scanner curl -s \
            "http://localhost:8080/OTHER/report/?format=html&title=ZAP%20Alert%20Report&template=traditional-html&theme=dark&description=Relatorio%20de%20Seguranca" \
            -o /zap/wrk/alert-report.html

      # 9️⃣ Verificar se os relatórios foram gerados
      - name: List ZAP reports
        run: ls -lh zap_reports

      # 🔟 Verificar vulnerabilidades no JSON
      - name: Parse JSON and fail if HIGH or CRITICAL found
        run: |
          echo "🔍 Analisando relatório JSON..."
          if [ ! -f "zap_reports/report.json" ]; then
            echo "⚠️ Arquivo report.json não encontrado."
            exit 0
          fi

          HIGH_COUNT=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' zap_reports/report.json)
          CRITICAL_COUNT=$(jq '[.site[].alerts[] | select(.risk == "Critical")] | length' zap_reports/report.json)

          echo "⚠️ Vulnerabilidades High: $HIGH_COUNT"
          echo "🚨 Vulnerabilidades Critical: $CRITICAL_COUNT"

          if [ "$HIGH_COUNT" -gt 0 ] || [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Vulnerabilidades graves detectadas."
            exit 1
          fi

      # 🔟 Upload dos relatórios como artefato
      - name: Upload ZAP reports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap_reports/

      # 🔚 Cleanup
      - name: Cleanup
        if: always()
        run: |
          docker rm -f clickseguro-app || true
          docker rm -f zap-scanner || true
          docker network rm zapnet || true
