name: OWASP ZAP DAST Scan

on:
  push:
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Construir imagem da aplicação
      - name: Build app Docker image
        run: docker build -t clickseguro-app .

      # 4️⃣ Subir container da aplicação
      - name: Run application container
        run: |
          docker run -d --network host --name clickseguro-app clickseguro-app
          sleep 10

      # 5️⃣ Criar pasta para relatórios e ajustar permissões
      - name: Prepare writable folder for reports
        run: |
          mkdir -p zap
