name: OWASP ZAP DAST Scan

on:
  push:
  pull_request:

jobs:
  securityscanjob:
    name: OWASP ZAP Automation Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app Docker image
        run: docker build -t clickseguro-app .

      - name: Create Docker network
        run: docker network create zapnet

      - name: Run application container
        run: |
          docker run -d --name clickseguro-app --network zapnet clickseguro-app
          echo "Aguardando app subir..."
          for i in {1..30}; do
            if curl -sSf http://clickseguro-app:8080 >/dev/null; then
              echo "✅ App está acessível"
              break
            fi
            echo "⏳ Esperando app..."
            sleep 2
          done

      - name: Prepare writable folder for reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      - name: Run OWASP ZAP Automation Framework
        run: |
          docker run --rm --network zapnet \
            -v ${{ github.workspace }}/zap_reports:/zap/wrk \
            -v ${{ github.workspace }}/zap-plan.yaml:/zap/zap-plan.yaml \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /zap/zap-plan.yaml

      - name: List ZAP reports
        run: ls -lh zap_reports

      - name: Upload ZAP reports as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap_reports/

      - name: Cleanup
        if: always()
        run: |
          docker rm -f clickseguro-app || true
          docker network rm zapnet || true
