name: OWASP ZAP DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura o Docker Buildx (necessário para builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build da imagem da aplicação Node
      - name: Build app Docker image
        run: docker build -t clickseguro:ci -f Dockerfile .

      # 4️⃣ Cria rede Docker isolada
      - name: Create docker network
        run: docker network create zap-net || true

      # 5️⃣ Executa container da aplicação em background
      - name: Run application container
        run: docker run -d --name clickseguro-app --network zap-net clickseguro:ci

      # 6️⃣ Aguarda até que a aplicação esteja acessível
      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if docker run --rm --network zap-net byrnedo/alpine-curl -sS http://clickseguro-app:8080 >/dev/null 2>&1; then
              echo "✅ Aplicação está pronta!"
              exit 0
            fi
            echo "⏳ Aguardando aplicação... ($i)"
            sleep 2
          done
          echo "❌ Aplicação não respondeu a tempo." && exit 1

      # 7️⃣ Cria e ajusta permissões da pasta de relatórios
      - name: Prepare writable folder for reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      # 8️⃣ Executa o OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network zap-net \
            -v ${{ github.workspace }}/zap_reports:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://clickseguro-app:8080 -r report.html -j report.json -I

      # 9️⃣ Verifica se os arquivos de relatório foram gerados
      - name: Check generated reports
        run: |
          echo "📄 Conteúdo do diretório zap_reports:"
          ls -l zap_reports || true

      # 🔟 Analisa o JSON e falha o pipeline se houver vulnerabilidades High ou Critical
      - name: Parse JSON and fail if HIGH or CRITICAL found
        run: |
          echo "📊 Analisando relatório JSON..."
          TOTAL=$(jq '[.site[]?.alerts[]?] | length' zap_reports/report.json)
          ALERTS_JSON=$(jq '[.site[]?.alerts[]?]' zap_reports/report.json)
          HIGH=$(echo "$ALERTS_JSON" | jq '[.[] | select(.risk == "High")] | length')
          CRIT=$(echo "$ALERTS_JSON" | jq '[.[] | select(.risk == "Critical")] | length')
          MEDIUM=$(echo "$ALERTS_JSON" | jq '[.[] | select(.risk == "Medium")] | length')
          LOW=$(echo "$ALERTS_JSON" | jq '[.[] | select(.risk == "Low")] | length')
          echo "🔸 Total: $TOTAL | Critical=$CRIT | High=$HIGH | Medium=$MEDIUM | Low=$LOW"
          if [ "$HIGH" -gt 0 ] || [ "$CRIT" -gt 0 ]; then
            echo "::error ::🚨 Vulnerabilidades High/Critical detectadas. Falhando pipeline."
            exit 1
          fi
          echo "✅ Nenhuma vulnerabilidade crítica encontrada."

      # 1️⃣1️⃣ Faz upload dos relatórios como artefato no GitHub
      - name: Upload ZAP reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap_reports
          path: zap_reports/

      # 1️⃣2️⃣ Limpa containers e rede, mesmo se der erro
      - name: Cleanup
        if: always()
        run: |
          docker rm -f clickseguro-app || true
          docker network rm zap-net || true
