name: OWASP ZAP DAST Scan

on:
  push:
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Construir imagem da aplicação Node.js
      - name: Build app Docker image
        run: docker build -t clickseguro-app .

      # 4️⃣ Executar container da aplicação
      - name: Run application container
        run: |
          docker run -d --network host --name clickseguro-app clickseguro-app
          sleep 10  # tempo para app iniciar

      # 5️⃣ Criar pasta para relatórios
      - name: Prepare writable folder for reports
        run: mkdir -p zap_reports

      # 6️⃣ Rodar OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network host \
            -v ${{ github.workspace }}/zap_reports:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            /bin/sh -c "zap-baseline.py -t http://localhost:8080 -r report.html -J report.json -w report.md -I || true"

      # 7️⃣ Checar se os relatórios foram gerados
      - name: Check generated reports
        run: |
          ls -lh zap_reports
          echo "Relatórios ZAP disponíveis em zap_reports/"

      # 8️⃣ Analisar JSON e falhar se vulnerabilidades High/Critical forem detectadas
      - name: Parse JSON and fail if HIGH or CRITICAL found
        run: |
          echo "🔍 Analisando relatório JSON..."
          if [ ! -f "zap_reports/report.json" ]; then
            echo "❌ Arquivo report.json não encontrado!"
            exit 1
          fi

          HIGH_COUNT=$(jq '[.site[].alerts[] | select(.risk == "High")] | length' zap_reports/report.json)
          CRITICAL_COUNT=$(jq '[.site[].alerts[] | select(.risk == "Critical")] | length' zap_reports/report.json)

          echo "⚠️ Vulnerabilidades High: $HIGH_COUNT"
          echo "🚨 Vulnerabilidades Critical: $CRITICAL_COUNT"

          if [ "$HIGH_COUNT" -gt 0 ] || [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Vulnerabilidades de alta severidade detectadas. Falhando pipeline..."
            exit 1
          fi

      # 9️⃣ Fazer upload dos relatórios como artefatos
      - name: Upload ZAP reports as artifact
        if: always()  # mesmo se o job falhar
        uses: actions/upload-artifact@v4
        with:
          name: zap_reports
          path: zap_reports/

      # 🔟 Encerrar e limpar containers
      - name: Cleanup
        if: always()
        run: docker rm -f clickseguro-app || true
